services:
  save-on-file:
    build: .
    ports:
      - "5555:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${DRIVE_PATH}/files:/usr/src/app/files
    networks:
      - my-network
    env_file:
      - .env

networks:
  my-network:
    driver: bridge