services:
  save-on-file:
    build: .
    ports:
      - "5555:5555"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../../drive/files:/usr/src/app/files
    networks:
      - my-network

networks:
  my-network:
    driver: bridge